exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex('product').del()
    .then(function () {
      // Inserts seed entries
      return knex('product').insert([
        {
          id: 1,
          seller_id: 1,
          hot_pick: true,
          status: 'available',
          name: 'Jordan 1 Retro High',
          details: 'Jordan Brand connected with Parisian fashion house Dior to create history with the Jordan 1 Retro High Dior, now available on StockX. This is the first time that Jordan has collaborated with a legacy fashion label like Dior, making this release one for the books. This release was limited to only 8,500 pairs, each pair individually numbered.',
          auth_status: true,
          brand: 'Nike',
          size: 9,
          color: 'White',
          make: 'Jordan 1',
          model: 'Dior High',
          year: 2020,
          price: 8002,
          condition: 'New',
          receipt: '',
          image1: '/productimages/dior/dior1.jpg',
          image2: '/productimages/dior/dior2.jpg',
          image3: '/productimages/dior/dior3.jpg',
          image4: '/productimages/dior/dior4.jpg'

        },
        {
          id: 2,
          seller_id: 2,
          hot_pick: false,
          status: 'sold',
          name: "AIR JORDAN 1 MID 'ARMORY NAVY'",
          details: 'The Jordan 1 Mid Armory Navy features a white leather upper with dark navy overlays and Swooshes. At the ankle, black leather collars add a subtle contrast to the overlays. A Jordan Wings logo at the ankle and Jumpman woven label on the tongue complete the design.',
          auth_status: true,
          brand: 'Nike',
          size: 12,
          color: 'black, white',
          make: 'Jordan 1',
          model: 'Armory Navy',
          year: 2022,
          price: 275,
          condition: 'New',
          receipt: '',
          image1: '/productimages/armoryNavy/armory1.jpeg',
          image2: '/productimages/armoryNavy/armory2.jpeg',
          image3: '/productimages/armoryNavy/armory3.jpeg',
          image4: '/productimages/armoryNavy/armory4.jpeg'
        },
        {
          id: 3,
          seller_id: 3,
          hot_pick: false,
          status: 'available',
          name: "AIR JORDAN 1 MID SE 'CRIMSON TINT'",
          details: 'PUSHAS checks each pair of sneakers and guarantees every pair is authentic. We also verify all Australian Resellers on the platform.',
          auth_status: true,
          brand: 'Nike',
          size: 8,
          color: 'pink',
          make: 'Air Jordan 1',
          model: 'Crimson Tint',
          year: 2019,
          price: 422,
          condition: 'New',
          receipt: '',
          image1: '/productimages/Crimson/crimson1.jpeg',
          image2: '/productimages/Crimson/crimson2.jpeg',
          image3: '/productimages/Crimson/crimson3.jpeg',
          image4: '/productimages/Crimson/crimson4.jpeg'
        },
        {
          id: 4,
          seller_id: 4,
          hot_pick: false,
          status: 'sold',
          name: "AIR JORDAN 1 MID SE 'DIAMOND SHORTS'",
          details: 'The Air Jordan 1 Mid brings full-court style and premium comfort to an iconic look. Its Air-Sole unit cushions play on the hardwood, while the padded collar gives you a supportive feel.          ',
          auth_status: true,
          brand: 'Nike',
          size: 11,
          color: 'white',
          make: 'Air Jordan 1',
          model: 'Diamond Shorts',
          year: 2012,
          price: 326,
          condition: 'used',
          receipt: '',
          image1: '/productimages/Diamond/diamond1.jpeg',
          image2: '/productimages/Diamond/diamond2.jpeg',
          image3: '/productimages/Diamond/diamond3.jpeg',
          image4: '/productimages/Diamond/diamond4.jpeg'
        },
        {
          id: 5,
          seller_id: 5,
          hot_pick: true,
          status: 'available',
          name: 'Air Jordan 1 Hi FlyEase',
          details: "The Air Jordan 1 Hi FlyEase combines the coveted style of Michael Jordan's first signature sneaker with a quick and easy 1-handed entry system.There are no laces to tie, just a wraparound zip and 2 straps to secure a custom fit.",
          auth_status: true,
          brand: 'Nike',
          size: '9',
          color: 'white, red',
          make: 'Air Jordan 1',
          model: 'Hi FlyEase',
          year: 2022,
          price: 230,
          condition: 'New',
          receipt: '',
          image1: '/productimages/Flyease/fly1.jpeg',
          image2: '/productimages/Flyease/fly2.jpeg',
          image3: '/productimages/Flyease/fly3.jpeg',
          image4: '/productimages/Flyease/fly4.jpeg'
        },

        {
          id: 6,
          seller_id: 1,
          hot_pick: true,
          status: 'available',
          name: 'ADIDAS YEEZY BOOST 350 V2 CP9652',
          details: "THE YEEZY BOOST 350 V2 'BRED' BRINGS A CLASSIC COLORWAY TO ITS MINIMALIST CONSTRUCTION. THE SHOE'S UPPER IS BUILT WITH PRIMEKNIT, FINISHED IN BLACK AND HIGHLIGHTED BY THE SPLY-350 BRANDING ON THE SIDE WALL. MORE RED MARKS THE HEEL PULL-LOOP, WHILE ROPE LACES SECURE THE FIT. UNDERFOOT, A FULL-LENGTH BOOST MIDSOLE WRAPPED IN A BLACK RUBBER CAGE PROVIDES CUSHIONING. A RUBBER OUTSOLE WITH CUTOUTS PROVIDES TRACTION. SKU: CP9652 RELEASE DATE: 2 NOV 2017 COLOR: CORE BLACK/CORE BLACK/RED",
          auth_status: true,
          brand: 'Addidas',
          size: '9',
          color: 'black',
          make: 'Yeezy',
          model: 'Boost 350',
          year: 2022,
          price: 470,
          condition: 'New',
          receipt: '',
          image1: '/productimages/yeezy350/ye1.jpeg',
          image2: '/productimages/yeezy350/ye2.jpeg',
          image3: '/productimages/yeezy350/ye3.jpeg',
          image4: '/productimages/yeezy350/ye4.jpeg'
        },
        {
          id: 7,
          seller_id: 2,
          hot_pick: true,
          status: 'available',
          name: 'ADIDAS YEEZY BOOST 350 V2 YEEZREEL FW5191',
          details: "ADIDAS ORIGINALS YEEZY BOOST 350 V2 YEEZREEL NON-REFLECTIVE TAKES ON THE ADIDAS YEEZY BOOST 350 V2 HAS A SIMILAR LOOK TO THE SEMI FROZEN YELLOW YEEZY 350 V2 RELEASE",
          auth_status: true,
          brand: 'Addidas',
          size: 7,
          color: 'green',
          make: 'YEEZY',
          model: 'BOOST 350 V2 YEEZREEL FW5191',
          year: 2021,
          price: 184,
          condition: 'New',
          receipt: '',
          image1: '/productimages/yeezyboost/yeb1.jpeg',
          image2: '/productimages/yeezyboost/yeb2.jpeg',
          image3: '/productimages/yeezyboost/yeb1.jpeg',
          image4: '/productimages/yeezyboost/yeb1.jpeg'
        },
        {
          id: 8,
          seller_id: 1,
          hot_pick: true,
          status: 'available',
          name: 'NIKE AIR JORDAN 1 MID CHICAGO 554724-173',
          details: 'DRESSED IN THE "CHICAGO" COLOR SCHEME, THIS ITERATION OF THE NIKE AIR JORDAN 1 MID FEATURES THE SIGNATURE COLOR-BLOCKING OF WHITE, BLACK AND GYM RED. ON THE WHITE LEATHER UPPER ARE RED OVERLAYS AND BLACK DETAILING, WITH AN UNCONVENTIONAL WHITE HEEL.',
          auth_status: true,
          brand: 'Nike',
          size: 9,
          color: 'white, red',
          make: 'AIR JORDAN 1',
          model: 'MID CHICAGO 554724-173',
          year: 2005,
          price: 270,
          condition: 'New',
          receipt: '',
          image1: '/productimages/jordanchicago/chicago1.jpeg',
          image2: '/productimages/jordanchicago/chicago2.jpeg',
          image3: '/productimages/jordanchicago/chicago1.jpeg',
          image4: '/productimages/jordanchicago/chicago1.jpeg'
        },
        {
          id: 9,
          seller_id: 1,
          hot_pick: true,
          status: 'available',
          name: 'NIKE AIR JORDAN 5 RETRO OREO CT4838-011',
          details: "DRESSED IN A BLACK, WHITE, AND COOL GREY COLOR SCHEME. THIS AIR JORDAN 5 WILL LOOK LIKE THE ORIGINAL PAIR FEATURING A BLACK NUBUCK UPPER, GREY JUMPMAN TONGUES, TRANSLUCENT NETTING ON THE SIDES AND WHITE EMBROIDERED BRANDING ON THE HEELS.",
          auth_status: false,
          brand: 'Nike',
          size: 12,
          color: 'white, black',
          make: 'AIR JORDAN 5',
          model: 'RETRO OREO CT4838-011',
          year: 2019,
          price: 260,
          condition: 'New',
          receipt: '',
          image1: '/productimages/jordanretro/retro1.jpeg',
          image2: '/productimages/jordanretro/retro2.jpeg',
          image3: '/productimages/jordanretro/retro1.jpeg',
          image4: '/productimages/jordanretro/retro1.jpeg'
        },
      ]);
    });
};

